### ISSUE TITLE
Solr 3.5 + WP 3.3 - issue with schema. Core doesn't show up

### ISSUE THREAD

**Issue by fujipadam** [mattweber/solr-for-wordpress#30]
Hi - I found the following issue and will appreciate it if you can fix it

Environment: Centos 5.x 64 bit,  server= jetty,  solr: 3.5 multicore, Wordpress 3.3

Initial setup
1) Install WP and solrforwordpress plugin
2) install Solr with Jetty as multicore and start it
3) go to localhost:8083 and you will core0 and core1 as options on the admin

Test Schema
4) Copy schema.xml from solrforwordpress plugin into core0/conf
5) restart solr
6) go to local host:8083 and you will not see core0 anymore 
NOTE: same thing happens when I get the schema.xml from git

Test plugin
7)ignore the issue with core0 and enter its details in the plugin and Check Server comes back as Ping failed
8) use core1 instead of core0 (note core1 has default schema.xml and shows up in solr admin) . Same result of Ping failed

Thank you for this plugin and let me know if you have any questions on the setup

Fuji

**Comment by shaksi** [comment]
The reason solr wont start when used in multicore environment is because it does not contain the right config files whilst the single instance does so.

To resolve this issue I would copy over solr/conf/*.txt files to the core0/conf folder, reason being our schema files makes use of few of the txt files defined by default in the single instance.
Once you have copied those file over, the server should start as normal.

Regarding the ping, thats another issue and has more to do with the solrconfig.xml within the conf folder, in a single instance the PingRequestHandler is defined under /admin/ping but in multicore instances it is not defined so.

To resolve the issue add this to your solrconfig.xml inside the `<config>` section 

```
      <requestHandler name="/admin/ping" class="PingRequestHandler">
               <lst name="defaults">
                 <str name="qt">standard</str>
                 <str name="q">solrpingquery</str>
                 <str name="echoParams">all</str>
               </lst>
      </requestHandler>
```

Hope that helps.

**Comment by dustinrue** [comment]
You should check your logs, the schema might not work with 3.5 and is causing Solr to not start that instance.

**Comment by mattweber** [comment]
shaksi is correct, copy the txt files from the non-multicore example, setup the ping request handler and everything works fine.

**Comment by fujipadam** [comment]
1) the Multicore issue was fixed by moving the *.txt files as Shaskhi suggested Thanks :)
2) still having the ping failed issue. I moved to single core and still had the issue and then even moved to Solr 1.4 and Ping still fails (I am able to ping successfully using my browser) and the search comes up as unavailable.

**Comment by ghost** [comment]
I'm getting this error: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "text": Plugin init failure for [schema.xml] analyzer/filter: Error loading class 'solr.EnglishPorterFilterFactory'

Will shaksi's solutions fix this issue?

If so, what is the full path of this:  " copy over solr/conf/*.txt files  "

Is it: solr/example/solr/collection1/conf    ??
